
POST http://localhost/enroll
Content-Type: application/json
Authorization: Token 46898005350336ba116eb052dda659b973bf82e9

{
  "user_id": "3",
  "service_id": "3",
  "program_id": "2",
  "mentor_id": "1",
  "status": "Pending"
}